[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://127.0.0.1:3000",
  "http://127.0.0.1:3000/auth/callback",
  "http://localhost:3000",
  "http://localhost:3000/auth/callback"
]
